In [1]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn
import torch.optim as optim

In [2]:
df=pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [6]:
df["review"] = df["review"].str.lower()
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [7]:
def remove_urls(text):
    text = re.sub(r"http\S+|www\S+","",text)
    return text
    
df["review"] = df["review"].apply(remove_urls)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [8]:
def remove_punc(text):
    text = re.sub(r"[^A-Za-z0-9\s]","",text)
    return text
    
df["review"] = df["review"].apply(remove_punc)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production br br the filmin...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [9]:
def remove_htmltags(text):
    text = re.sub(r"<.*?>","",text)
    return text
    
df["review"] = df["review"].apply(remove_htmltags)
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production br br the filmin...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [10]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\manya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\manya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
def remove_stopwords(text):
    tokens=word_tokenize(text)
    stop_word=set(stopwords.words("english"))
    for i in tokens:
        if i in stop_word:
            text=text.replace(i,"")
    return text
df["review"]=df["review"].apply(remove_stopwords)

In [12]:
df

                                                  review sentiment
0      e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1       wderful ltle producti br br  filming techniqu...  positive
2       thought ths   wderful wy  spend tme   o hot s...  positive
3      bsclly res  fmly   lttle boy jke thks res  zom...  negative
4      petter mtte love   time  mey   vully stunng fi...  positive
...                                                  ...       ...
49995   thought ths move dd   rght good job t wsnt s ...  positive
49996  bd plot bd dlogue bd ctng dotc drectng  nnoyng...  negative
49997     ctholc tught n prochl elentry schools  nuns...  negative
49998  im gog    dgree   previous comnt  side  mlt   ...  negative
49999   one expects  str trek moves   hgh rt   fns  e...  negative

[49582 rows x 2 columns]

In [13]:
def stemming(text):
    ps=PorterStemmer()
    stem_words=[]
    tokens=word_tokenize(text)
    for i in tokens:
        st=ps.stem(i)
        stem_words.append(st)
    return " ".join(stem_words)
df["review"]=df["review"].apply(stemming)

In [14]:
df

                                                  review sentiment
0      e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1      wder ltle producti br br film techniqu unssum ...  positive
2      thought th wder wy spend tme o hot summer week...  positive
3      bsclli re fmli lttle boy jke thk re zomb close...  negative
4      petter mtte love time mey vulli stunng film wt...  positive
...                                                  ...       ...
49995  thought th move dd rght good job t wsnt s cret...  positive
49996  bd plot bd dlogu bd ctng dotc drectng nnoyng p...  negative
49997  ctholc tught n prochl elentri school nun tught...  negative
49998  im gog dgree previou comnt side mlt e secd rte...  negative
49999  one expect str trek move hgh rt fn expect move...  negative

[49582 rows x 2 columns]

In [15]:
le=LabelEncoder()
df["sentiment"]=le.fit_transform(df["sentiment"])
df

                                                  review  sentiment
0      e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1      wder ltle producti br br film techniqu unssum ...          1
2      thought th wder wy spend tme o hot summer week...          1
3      bsclli re fmli lttle boy jke thk re zomb close...          0
4      petter mtte love time mey vulli stunng film wt...          1
...                                                  ...        ...
49995  thought th move dd rght good job t wsnt s cret...          1
49996  bd plot bd dlogu bd ctng dotc drectng nnoyng p...          0
49997  ctholc tught n prochl elentri school nun tught...          0
49998  im gog dgree previou comnt side mlt e secd rte...          0
49999  one expect str trek move hgh rt fn expect move...          0

[49582 rows x 2 columns]

In [16]:
y=df["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [17]:
from sklearn.feature_extraction.text import  TfidfVectorizer
tf=TfidfVectorizer(max_features=5000)
X=tf.fit_transform(df["review"])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057177 stored elements and shape (49582, 5000)>

In [18]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057177 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515483024345262
  (0, 2868)	0.0936117999702081
  (0, 4940)	0.11467306921684882
  (0, 3002)	0.47200525710451824
  (0, 1274)	0.13579495563516442
  (0, 2288)	0.04949781497253455
  (0, 1932)	0.07912600706770702
  (0, 3550)	0.09639740406021617
  (0, 1361)	0.06162487526051707
  (0, 1962)	0.061560426499135894
  (0, 219)	0.08588918415080868
  (0, 1619)	0.07381703287290607
  (0, 4369)	0.041994175081156916
  (0, 4171)	0.17799680055182324
  (0, 3693)	0.03353218809938695
  (0, 4738)	0.2679893487333962
  (0, 3805)	0.04427608454269031
  (0, 4770)	0.058774041157922306
  (0, 1738)	0.037520872639411215
  (0, 4497)	0.07614064051809305
  (0, 3857)	0.1753881885556807
  (0, 1629)	0.06142443626611341
  (0, 1861)	0.07433132344021556
  (0, 3329)	0.06406816583736535
  (0, 3332)	0.08447544288010156
  :	:
  (49581, 4890)	0.1068234046295195
  (49581, 1541)	0.17582963029794152
  (49581, 4494)	0.09410074283150294
  (49581, 433)	0.11251661797175519
  (49581, 4277)	0.10905961990374913
  (49581, 1957)	0.09990750617145176
  (49581, 554)	0.08424223212710209
  (49581, 2186)	0.14180356030224497
  (49581, 2216)	0.0953560749616917
  (49581, 4347)	0.17508223969035314
  (49581, 4630)	0.11571236841873836
  (49581, 3647)	0.08733406864209714
  (49581, 4735)	0.12354129251955981
  (49581, 1976)	0.12795469923440583
  (49581, 526)	0.12479351009138054
  (49581, 2621)	0.1734136655239105
  (49581, 4458)	0.16002241768707068
  (49581, 2173)	0.18983807585269513
  (49581, 4033)	0.20100055348433288
  (49581, 340)	0.14784972154022608
  (49581, 2695)	0.17400817764858093
  (49581, 438)	0.1332353345481999
  (49581, 4980)	0.15095828555894397
  (49581, 1763)	0.15815323644832044
  (49581, 3489)	0.15197423490532808

In [19]:
features = tf.get_feature_names_out()
print(features[3538])

revew

In [20]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)
x_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3248346 stored elements and shape (39665, 5000)>

In [21]:
x_test.shape

(9917, 5000)

In [22]:
import torch
from torch.utils.data import TensorDataset,DataLoader
x_train=x_train.toarray()
x_test=x_test.toarray()
x_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.06314319, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(9917, 5000))

In [23]:
trainset=TensorDataset(
    torch.from_numpy(x_train).float(),
    torch.from_numpy(y_train.values).float()
)
testset=TensorDataset(
    torch.from_numpy(x_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [24]:
train_loader = DataLoader(trainset, shuffle=True, batch_size=64)
test_loader = DataLoader(testset, shuffle=True, batch_size=64)

In [25]:
class RNN(nn.Module):
    def __init__(self,input_size,hidden_size=256,num_layers=1):
        super().__init__()
        self.hidden_size=hidden_size
        self.num_layers=num_layers
        self.rnn=nn.RNN(input_size,hidden_size,num_layers,batch_first=True)
        self.fc=nn.Linear(hidden_size,1)
    def forward(self,x):
        h0=torch.zeros(self.num_layers,x.size(0),self.hidden_size)
        out,_=self.rnn(x,h0)
        out=self.fc(out[:,-1,:])
        return out

In [26]:
input_size = x_train.shape[1]
model = RNN(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

In [28]:
best_loss = float('inf')
epochs=20
for epoch in range(epochs):

    running_loss = 0

    model.train()

    for xb, yb in train_loader:

        optimizer.zero_grad()

        xb = xb.unsqueeze(1)

        outputs = model(xb)

        outputs = torch.sigmoid(outputs.squeeze())

        loss = criterion(outputs, yb)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    avg_loss = running_loss / len(train_loader)

    print(f"Epoch {epoch+1}, Loss = {avg_loss:.4f}")

    if avg_loss < best_loss:

        best_loss = avg_loss

        torch.save(model.state_dict(), "best_model.pth")

        print("Best model saved!")

Epoch 1, Loss = 0.3617
Best model saved!
Epoch 2, Loss = 0.2654
Best model saved!
Epoch 3, Loss = 0.2517
Best model saved!
Epoch 4, Loss = 0.2446
Best model saved!
Epoch 5, Loss = 0.2403
Best model saved!
Epoch 6, Loss = 0.2373
Best model saved!
Epoch 7, Loss = 0.2347
Best model saved!
Epoch 8, Loss = 0.2331
Best model saved!
Epoch 9, Loss = 0.2307
Best model saved!
Epoch 10, Loss = 0.2298
Best model saved!
Epoch 11, Loss = 0.2285
Best model saved!
Epoch 12, Loss = 0.2276
Best model saved!
Epoch 13, Loss = 0.2263
Best model saved!
Epoch 14, Loss = 0.2257
Best model saved!
Epoch 15, Loss = 0.2254
Best model saved!
Epoch 16, Loss = 0.2243
Best model saved!
Epoch 17, Loss = 0.2234
Best model saved!
Epoch 18, Loss = 0.2228
Best model saved!
Epoch 19, Loss = 0.2223
Best model saved!
Epoch 20, Loss = 0.2211
Best model saved!

In [29]:
model.eval()
with torch.no_grad():
    correct_vals = 0
    tot_vals = 0 
    for xb, yb in test_loader:
        xb = xb.unsqueeze(1)
        outputs = model(xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()
        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()
    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 85.42906120802662

85.429061 Accuracy

### LSTM approach

In [30]:
class LSTMModel(nn.Module):

    def __init__(self, input_size, hidden_size=256, num_layers=1):

        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True
        )

        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):

        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.lstm(x, (h0, c0))

        out = self.fc(out[:, -1, :])

        return out

In [31]:
input_size = x_train.shape[1]
model = LSTMModel(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 20

In [32]:
best_loss = float('inf')
for epoch in range(epochs):
    running_loss = 0
    model.train()
    for xb, yb in train_loader:
        optimizer.zero_grad()
        xb = xb.unsqueeze(1)
        outputs = model(xb)
        outputs = torch.sigmoid(outputs.squeeze())
        loss = criterion(outputs, yb)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    avg_loss = running_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{epochs}, Loss = {avg_loss:.4f}")
    if avg_loss < best_loss:
        best_loss = avg_loss
        torch.save(model.state_dict(), "best_lstm_model.pth")
        print("Best LSTM model saved!")

Epoch 1/20, Loss = 0.3766
Best LSTM model saved!
Epoch 2/20, Loss = 0.2614
Best LSTM model saved!
Epoch 3/20, Loss = 0.2452
Best LSTM model saved!
Epoch 4/20, Loss = 0.2361
Best LSTM model saved!
Epoch 5/20, Loss = 0.2297
Best LSTM model saved!
Epoch 6/20, Loss = 0.2234
Best LSTM model saved!
Epoch 7/20, Loss = 0.2166
Best LSTM model saved!
Epoch 8/20, Loss = 0.2088
Best LSTM model saved!
Epoch 9/20, Loss = 0.2006
Best LSTM model saved!
Epoch 10/20, Loss = 0.1902
Best LSTM model saved!
Epoch 11/20, Loss = 0.1773
Best LSTM model saved!
Epoch 12/20, Loss = 0.1618
Best LSTM model saved!
Epoch 13/20, Loss = 0.1423
Best LSTM model saved!
Epoch 14/20, Loss = 0.1195
Best LSTM model saved!
Epoch 15/20, Loss = 0.0956
Best LSTM model saved!
Epoch 16/20, Loss = 0.0707
Best LSTM model saved!
Epoch 17/20, Loss = 0.0493
Best LSTM model saved!
Epoch 18/20, Loss = 0.0320
Best LSTM model saved!
Epoch 19/20, Loss = 0.0190
Best LSTM model saved!
Epoch 20/20, Loss = 0.0108
Best LSTM model saved!

In [33]:
model.load_state_dict(torch.load("best_lstm_model.pth"))
model.eval()
with torch.no_grad():
    correct_vals = 0
    tot_vals = 0
    for xb, yb in test_loader:
        xb = xb.unsqueeze(1)
        outputs = model(xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()
        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()
accuracy = correct_vals / tot_vals * 100
print(f"Test Accuracy = {accuracy:.2f}%")

Test Accuracy = 85.12%